### ISSUE TITLE
相册就一个文件要上传 , 一只调 API接口 fastupload 不上传

### ISSUE THREAD

**Issue by RedForc** [dji-sdk/Cloud-API-Demo-Web#10]
无人机的相册里就一个文件要上传OSS 
不停的调 API   request uri: /media/api/v1/workspaces/e3dea0f5-37f2-4d79-ae58-490af3228069/fast-upload
后台 查数据库 无文件  返回: 
        ResponseResult.error(file.getFingerprint() + "don't exist.");
 然后一直掉接口  fast-upload  不上传

前后端都是 main分支

**Comment by wukuili** [comment]
请问怎么解决的呢？我现在也遇到了同样的问题
