### ISSUE TITLE
登录pilot-login，为什么报Cannot read properties of undefined (reading 'platformVerifyLicense')

### ISSUE THREAD

**Issue by NeXT1995** [dji-sdk/Cloud-API-Demo-Web#32]
platformVerifyLicense (appId:string, appKey:string, appLicense:string): boolean {
    return returnBool(window.djiBridge.platformVerifyLicense(appId, appKey, appLicense))
  },
  
  TypeError: Cannot read properties of undefined (reading 'platformVerifyLicense')
    at Object.platformVerifyLicense (pilot-bridge.ts:163:43)

这个是缺少什么依赖吗？

**Comment by BetterLevi** [comment]
@NeXT1995 您好 请问怎么解决的

**Comment by Yaozefen** [comment]
@NeXT1995 我也遇到了一样的问题，请问你这边是怎么解决的
