### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by blyspyder** [dji-sdk/Cloud-API-Demo-Web#4]
1068 verbose stack Error: Missing required argument #1
1068 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
1068 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
1068 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
1068 verbose stack     at /usr/share/npm/lib/install/deps.js:457:7
1068 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
1068 verbose stack     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
1068 verbose stack     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
1068 verbose stack     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
1068 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
1068 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
1069 verbose cwd /home/bly/project/dji_uav/Cloud-API-Demo-Web-main
1070 error Linux 5.4.0-117-generic
1071 error argv "/usr/bin/node" "/usr/bin/npm" "install"
1072 error node v8.10.0
1073 error npm  v3.5.2
1074 error code EMISSINGARG
1075 error typeerror Error: Missing required argument #1
1075 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
1075 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
1075 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
1075 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
1075 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
1075 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
1075 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
1075 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
1075 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
1075 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
1076 error typeerror This is an error with npm itself. Please report this error at:
1076 error typeerror     <http://github.com/npm/npm/issues>
1077 verbose exit [ 1, true ]

运行npm install后出现上述错误，这个是版本问题还是什么问题呢？

**Comment by DJIsean** [comment]
似乎是node版本问题导致的报错，建议更新到最新版本，重新install。
