### ISSUE TITLE
uri: /manage/api/v1/devices//binding error - looks like a typo?

### ISSUE THREAD

**Issue by dronematt** [dji-sdk/Cloud-API-Demo-Web#7]
loud_api_sample_1  | 2022-12-24 04:25:45.613 DEBUG 7 --- [nio-6789-exec-4] c.dji.sample.component.AuthInterceptor   : request uri: /manage/api/v1/devices//binding
cloud_api_sample_1  | 2022-12-24 04:25:45.616 DEBUG 7 --- [nio-6789-exec-4] c.dji.sample.component.AuthInterceptor   : request uri: /error
cloud_api_sample_1  | 2022-12-24 04:25:46.409  INFO 7 --- [ask-scheduler-9] c.d.s.w.s.impl.FlightTaskServiceImpl     : Check the timed jobs of the wayline. null

**Comment by DJIsean** [comment]
window.djiBridge.platformGetRemoteControllerSN() This method does not recognize the remote control SN, it is recommended to restart the remote control.
