### ISSUE TITLE
pilot2 无法上云 device not connect

### ISSUE THREAD

**Issue by qinc998** [dji-sdk/Cloud-API-Demo-Web#9]
pilot2上不了云，只有cloud无法连接，console里只有一个错误：device not connect，network里没有报错，后端也没有报错。
在文档中找到了jsbridge上云模块的相关api，并发现前端中没有调用过上云模块的连接方法，不知道有没有关系。
麻烦各位看看，可私信提供地址测试
![Dingtalk_20230331183110](https://user-images.githubusercontent.com/36267257/229097692-1a647eb3-1743-46ca-a4bc-c329044544ee.jpg)
![2](https://user-images.githubusercontent.com/36267257/229097745-10c99d7d-86ee-49aa-8832-601b0523097a.jpg)
![Dingtalk_20230331183632](https://user-images.githubusercontent.com/36267257/229098206-bb0f6b45-b646-48c3-bd62-54345a2c4c5a.jpg)

**Comment by Tit1e** [comment]
请问后面怎么解决的，我也遇到了相同的问题

**Comment by hdjhdjhdj** [comment]
console里只有一个错误：device not connect，这个错误是大疆app返回的，调用桥接通过returnString返回的

**Comment by F00dP00l** [comment]
您好，我遇到了相同的错误，看到您这边已经completed了是否能够分享一下解决方案

**Comment by hdjhdjhdj** [comment]
这不算错误。
无人机没有连接时，调用桥接apiPilot.getAircraftSN()，就会有这个报错

**Comment by F00dP00l** [comment]
> 这不算错误。 无人机没有连接时，调用桥接apiPilot.getAircraftSN()，就会有这个报错

感谢 确实定位到了此信息的出处

**Comment by guowushi** [comment]
解决了吗
